# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Do I Even CS?
author: Aaron Young
email: asw.young@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a normal guy trying to make sense of the world of CS
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://aaronyoung.me" # the base hostname & protocol for your site
twitter_username: aarony422
github_username:  aarony422
paginate: 10
paginate_path: "/page:num/"
permalink: "/:year/:month/:day/:title/"

# Build settings
markdown: kramdown
gems: [jekyll-sitemap]

# http://www.minddust.com/post/alternative-tags-and-categories-on-github-pages/
# categories and tags
collections:
  my_categories:
    output: true
    permalink: /category/:name/
  my_tags:
    output: true
    permalink: /tag/:name/
